/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "oauth.redirect": [
        {
            "name": "provider"
        }
    ],
    "oauth.callback": [
        {
            "name": "provider"
        }
    ],
    "connected-accounts.destroy": [
        {
            "name": "id"
        }
    ],
    "user-password.set": [],
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "api-tokens.index": [],
    "api-tokens.store": [],
    "api-tokens.update": [
        {
            "name": "token"
        }
    ],
    "api-tokens.destroy": [
        {
            "name": "token"
        }
    ],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "v1": [],
    "v1password.email": [],
    "deliveries.index": [],
    "deliveries.store": [],
    "deliveries.show": [
        {
            "name": "delivery",
            "binding": "id"
        }
    ],
    "deliveries.update": [
        {
            "name": "delivery"
        }
    ],
    "deliveries.destroy": [
        {
            "name": "delivery"
        }
    ],
    "notifications.index": [],
    "notifications.create": [],
    "notifications.store": [],
    "notifications.show": [
        {
            "name": "notification"
        }
    ],
    "notifications.edit": [
        {
            "name": "notification"
        }
    ],
    "notifications.update": [
        {
            "name": "notification"
        }
    ],
    "notifications.destroy": [
        {
            "name": "notification"
        }
    ],
    "home": [],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.show": [
        {
            "name": "product"
        }
    ],
    "products.edit": [
        {
            "name": "product"
        }
    ],
    "products.update": [
        {
            "name": "product"
        }
    ],
    "products.destroy": [
        {
            "name": "product"
        }
    ],
    "recipes.index": [],
    "recipes.create": [],
    "recipes.store": [],
    "recipes.show": [
        {
            "name": "recipe",
            "binding": "slug"
        }
    ],
    "recipes.edit": [
        {
            "name": "recipe"
        }
    ],
    "recipes.update": [
        {
            "name": "recipe"
        }
    ],
    "recipes.destroy": [
        {
            "name": "recipe"
        }
    ],
    "cartItems.index": [],
    "cart.create": [],
    "cartItem.store": [],
    "cart.show": [
        {
            "name": "cartItem"
        }
    ],
    "cart.edit": [
        {
            "name": "cartItem"
        }
    ],
    "cartItem.update": [
        {
            "name": "cartItem"
        }
    ],
    "cartItem.destroy": [
        {
            "name": "cartItem",
            "binding": "id"
        }
    ],
    "orders.index": [],
    "orders.create": [],
    "orders.store": [],
    "orders.show": [
        {
            "name": "order",
            "binding": "id"
        }
    ],
    "orders.edit": [
        {
            "name": "order"
        }
    ],
    "orders.update": [
        {
            "name": "order"
        }
    ],
    "orders.destroy": [
        {
            "name": "order"
        }
    ],
    "orders.payments.create": [
        {
            "name": "order",
            "binding": null
        }
    ],
    "orders.payments.store": [
        {
            "name": "order",
            "binding": null
        }
    ],
    "customer.store": [],
    "customer.update": [
        {
            "name": "customer",
            "binding": "id"
        }
    ],
    "invoices.index": [],
    "invoices.create": [],
    "invoices.store": [],
    "invoices.show": [
        {
            "name": "invoice"
        }
    ],
    "invoices.edit": [
        {
            "name": "invoice"
        }
    ],
    "invoices.update": [
        {
            "name": "invoice"
        }
    ],
    "invoices.destroy": [
        {
            "name": "invoice"
        }
    ],
    "vendors.index": [],
    "vendors.create": [],
    "vendors.store": [],
    "vendors.show": [
        {
            "name": "vendor",
            "binding": "slug"
        }
    ],
    "vendors.edit": [
        {
            "name": "vendor",
            "binding": "slug"
        }
    ],
    "vendors.update": [
        {
            "name": "vendor",
            "binding": "slug"
        }
    ],
    "vendors.destroy": [
        {
            "name": "vendor",
            "binding": "slug"
        }
    ],
    "deals.index": [],
    "deals.create": [],
    "deals.store": [],
    "deals.show": [
        {
            "name": "deal",
            "binding": "id"
        }
    ],
    "deals.edit": [
        {
            "name": "deal",
            "binding": "id"
        }
    ],
    "deals.update": [
        {
            "name": "deal",
            "binding": "id"
        }
    ],
    "deals.destroy": [
        {
            "name": "deal",
            "binding": "id"
        }
    ],
    "products.reviews.index": [
        {
            "name": "product",
            "binding": null
        }
    ],
    "products.reviews.create": [
        {
            "name": "product",
            "binding": null
        }
    ],
    "products.reviews.store": [
        {
            "name": "product",
            "binding": null
        }
    ],
    "products.reviews.show": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "review",
            "binding": null
        }
    ],
    "products.reviews.edit": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "review",
            "binding": null
        }
    ],
    "products.reviews.update": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "review",
            "binding": null
        }
    ],
    "products.reviews.destroy": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "review",
            "binding": null
        }
    ],
    "products.likes.index": [
        {
            "name": "product",
            "binding": null
        }
    ],
    "products.likes.create": [
        {
            "name": "product",
            "binding": null
        }
    ],
    "products.likes.store": [
        {
            "name": "product",
            "binding": null
        }
    ],
    "products.likes.show": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "like",
            "binding": null
        }
    ],
    "products.likes.edit": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "like",
            "binding": null
        }
    ],
    "products.likes.update": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "like",
            "binding": null
        }
    ],
    "products.likes.destroy": [
        {
            "name": "product",
            "binding": null
        },
        {
            "name": "like",
            "binding": null
        }
    ],
    "payment.verify": [],
    "orders.invoice": [
        {
            "name": "order",
            "binding": "id"
        }
    ],
    "deliveries.create": [],
    "deliveries.edit": [
        {
            "name": "delivery"
        }
    ],
    "delivery_person.dashboard": [],
    "deliveries.accept": [
        {
            "name": "delivery",
            "binding": "id"
        }
    ],
    "deliveries.complete": [
        {
            "name": "delivery",
            "binding": "id"
        }
    ],
    "deliveries.start": [
        {
            "name": "delivery",
            "binding": "id"
        }
    ],
    "vendor.dashboard": [],
    "switch-role": [
        {
            "name": "role"
        }
    ]
}
}
export {};
